---
name: Test Ansible Code
on: [push, pull_request]
jobs:
  test-ansible:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible-lint yamllint ansible

    - name: Ansible Lint
      run: |
        ansible-lint site.yml

